app = "app-zbeshewo-divine-firefly-2718"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8000"
  PYTHON_VERSION = "3.10.12"
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"

[processes]
  app = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
